export const VIEW_INPUT_CHANGES = "VIEW_INPUT_CHANGES";
export const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
export const FILTER_COUNTRIES = "FILTER_COUNTRIES";
export const GET_COUNTRIES_REQUEST = "GET_COUNTRIES_REQUEST";
export const GET_COUNTRIES_FAILED = "GET_COUNTRIES_FAILED";
export const CLEAR_COUNTRIES = "CLEAR_COUNTRIES";